# Generated by Django 2.2.10 on 2021-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='jobarea',
        ),
    ]
