# Generated by Django 2.2.10 on 2021-07-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_jobarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pannumber',
            new_name='cpannumber',
        ),
    ]
