# Generated by Django 2.2.10 on 2021-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='files',
            field=models.FileField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
