# Generated by Django 2.2.10 on 2021-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='files',
        ),
        migrations.AddField(
            model_name='company',
            name='agree',
            field=models.FileField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='other',
            field=models.FileField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='panvat',
            field=models.FileField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='regfiles',
            field=models.FileField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
