# Generated by Django 2.2.10 on 2021-08-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210828_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agree',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='panvat',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='regfiles',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
