# Generated by Django 2.2.10 on 2021-09-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210828_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gagree',
            field=models.FileField(null=True, upload_to='guard_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gothers',
            field=models.FileField(null=True, upload_to='guard_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gpan',
            field=models.FileField(null=True, upload_to='guard_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gphoto',
            field=models.FileField(null=True, upload_to='guard_documents/'),
        ),
    ]
