# Generated by Django 2.2.10 on 2021-09-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210901_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agree',
            field=models.FileField(null=True, upload_to='company_documents/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other',
            field=models.FileField(null=True, upload_to='company_documents/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='panvat',
            field=models.FileField(null=True, upload_to='company_documents/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='regfiles',
            field=models.FileField(null=True, upload_to='company_documents/'),
        ),
        migrations.CreateModel(
            name='employee_company_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
