# Generated by Django 2.2.10 on 2021-09-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210904_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_company_relation',
            name='company_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
