# Generated by Django 2.2.10 on 2021-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employee_company_relation_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyname',
            field=models.CharField(max_length=50),
        ),
    ]
