# Generated by Django 2.2.10 on 2021-09-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210904_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_posting_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('company_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
