# Generated by Django 2.2.10 on 2021-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employee_posting_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='idnumber',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
